### ISSUE TITLE
error: can't exec 'metal' (No such file or directory)

### ISSUE THREAD

**Issue by atacank** [shu223/iOS8-Sampler#9]
I deleted the directory in DerivedData but it doesn't work for me.

I got this error message:

CompileMetalFile libs/AAPL/MetalBasic3D/shaders.metal
    cd "/Users/gurkan/Desktop/iOS8-Sampler-master 2"
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    metal -arch air64 -emit-llvm -c -gline-tables-only -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk -ffast-math -serialize-diagnostics /Users/gurkan/Library/Developer/Xcode/DerivedData/iOS8Sampler-adcbobzemlxmugekmrfsoluayscw/Build/Intermediates/iOS8Sampler.build/Debug-iphonesimulator/iOS8Sampler.build/Metal/shaders.dia -o /Users/gurkan/Library/Developer/Xcode/DerivedData/iOS8Sampler-adcbobzemlxmugekmrfsoluayscw/Build/Intermediates/iOS8Sampler.build/Debug-iphonesimulator/iOS8Sampler.build/Metal/shaders.air /Users/gurkan/Desktop/iOS8-Sampler-master\ 2/libs/AAPL/MetalBasic3D/shaders.metal

error: can't exec 'metal' (No such file or directory)
Command metal failed with exit code 71

**Comment by psobko** [comment]
If you're using the simulator make sure you are using the simulator scheme, you can't run metal on a simulator as far as I know.

**Comment by atacank** [comment]
Thank you psobko. I was working on simulator.
